// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useInnerHeight(param) {
  var match = React.useState((function () {
          return window.innerHeight;
        }));
  var setH = match[1];
  React.useEffect((function () {
          var listener = function (param) {
            return Curry._1(setH, (function (param) {
                          return window.innerHeight;
                        }));
          };
          window.addEventListener("resize", listener);
          return (function (param) {
                    window.removeEventListener("resize", listener);
                    return /* () */0;
                  });
        }), ([]));
  return match[0];
}

exports.useInnerHeight = useInnerHeight;
/* react Not a pure module */
