// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function container($staropt$star) {
  var height = $staropt$star !== undefined ? $staropt$star : 50;
  return Css.style(/* :: */[
              Css.minHeight(Css.px(height)),
              /* :: */[
                Css.maxHeight(Css.px(height)),
                /* :: */[
                  Css.padding(Css.px(10)),
                  /* :: */[
                    Css.borderBottom(Css.px(1), Css.solid, Css.hex("efefef")),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

var Styles = /* module */[/* container */container];

function TableRow(Props) {
  var children = Props.children;
  var height = Props.height;
  return React.createElement("div", {
              className: container(height)
            }, React.createElement("span", undefined, "Table Row: "), children);
}

var make = TableRow;

exports.Styles = Styles;
exports.make = make;
/* Css Not a pure module */
